### ISSUE TITLE
redis test timing out

### ISSUE THREAD

**Issue by drnic** [mperham/girl_friday#23]
```
$ bundle exec rake
/Users/drnic/.rvm/gems/jruby-1.6.3@gf/gems/flexmock-minitest-1.0.1/lib/flexmock/minitest.rb:4 warning: already initialized constant VERSION
jruby 1.6.3 (ruby-1.9.2-p136) (2011-07-07 965162f) (Java HotSpot(TM) 64-Bit Server VM 1.6.0_26) [darwin-x86_64-java]
Run options: --seed 51191

# Running tests:

........E....

Finished tests in 2.466000s, 5.2717 tests/s, 11.7599 assertions/s.

  1) Error:
test_should_persist_with_redis_instance(TestGirlFriday):
Timeout::Error: Timeout::Error
    /Users/drnic/Projects/gems/girl_friday/test/timed_queue.rb:27:in `timed_pop'
    /Users/drnic/Projects/gems/girl_friday/test/timed_queue.rb:22:in `timed_pop'
    /Users/drnic/Projects/gems/girl_friday/test/helper.rb:22:in `async_test'
    /Users/drnic/Projects/gems/girl_friday/test/test_girl_friday.rb:132:in `test_should_persist_with_redis_instance'
    org/jruby/RubyBasicObject.java:1684:in `__send__'

13 tests, 29 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
```

I have redis running:

```
$ ps ax | grep redis
 1517   ??  R      6:32.07 /usr/local/Cellar/redis/2.2.11/bin/redis-server /usr/local/etc/redis.conf
56251 s006  R+     0:00.00 grep redis
```

Thoughts on what to do to get this test passing?

**Comment by jc00ke** [comment]
I see this happening too, but I'm not sure what's causing it. When I modify the test to puts `msg` sometimes it'll output all 100, other times only 2 then it hangs.

**Comment by jc00ke** [comment]
Does this test always fail for you? I'm not able to reproduce it (jRuby 1.6.3 on OpenJDK 1.6.0_22) with same `--seed`. In fact, the only time I saw it fail was the first time I ran it. All subsequent runs it passed.

**Comment by mperham** [comment]
Can you guys try 0.9.5 and see if this is still an issue?

**Comment by drnic** [comment]
I pulled down master, ran tests and all tests pass. I believe I also upgraded to latest redis today too.

**Comment by mperham** [comment]
Thanks, doc!
