### ISSUE TITLE
can't convert Symbol into Integer (TypeError) during start

### ISSUE THREAD

**Issue by masterkain** [mperham/girl_friday#36]
I updated my code according the to latest commits, results below:

```
/Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/girl_friday-3c97ba78f22c/lib/girl_friday/persistence.rb:26:in `[]': can't convert Symbol into Integer (TypeError)
  from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/girl_friday-3c97ba78f22c/lib/girl_friday/persistence.rb:26:in `initialize'
  from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/girl_friday-3c97ba78f22c/lib/girl_friday/work_queue.rb:21:in `new'
  from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/girl_friday-3c97ba78f22c/lib/girl_friday/work_queue.rb:21:in `initialize'
  from /Users/kain/Sites/myproj/config/initializers/girl_friday.rb:22:in `new'
  from /Users/kain/Sites/myproj/config/initializers/girl_friday.rb:22:in `<top (required)>'
```

Sample worker:

```
uri = URI.parse(Settings.app.redis.uri)
redis_pool = ConnectionPool.new(:size => 5, :timeout => 5) { Redis.new(:host => uri.host, :port => uri.port, :password => uri.password) }

TRACK_NOW_PLAYING_QUEUE = GirlFriday::WorkQueue.new(:scrobble, size: 2, store: GirlFriday::Store::Redis, store_config: [{ pool: redis_pool }]) do |packet|
```

**Comment by ryanlecompte** [comment]
Hi masterkain,

Your problem is that you are passing a list to the :store_config option instead of just a normal hash. You should specify it as :store_config => {:pool => redis_pool}, right now you have :store_config => [{:pool => redis_pool}]. I've tested it locally and it works when using just a plain unwrapped hash. Please re-open the issue if you still have trouble.

**Comment by masterkain** [comment]
Yes that's the problem but you may want to update the Readme then.

Cheers

**Comment by ryanlecompte** [comment]
Ah, will do. Thanks!
