### ISSUE TITLE
release latest as 0.9.8, please?

### ISSUE THREAD

**Issue by ghost** [mperham/girl_friday#57]
Several problems have been fixed since the last release (0.9.7). Gathering these into a release would be helpful.

The fix I need is the updated dependency on connection_pool (from 0.1.0 to 0.9.0). I've built a gem that depends on girl_friday, and having the wrong connection_pool dragged in to my users' apps is problematic.

**Comment by jc00ke** [comment]
I'll run all the specs real quick. I don't see why we can't push. @mperham that sound ok?

**Comment by mperham** [comment]
Fine by me.  A release has been on my todo list for about a month now.

**Comment by mperham** [comment]
Should it be 0.9.8 or 0.10.0?

**Comment by jc00ke** [comment]
0.1.0 sounds good.

**Comment by jc00ke** [comment]
Er, you know what I meant. 0.10.0

**Comment by jc00ke** [comment]
```

15:02:13 jesse@chino:~/projects/girl_friday (git:master:9edea0f)  jruby-1.6.7.2@gf 
∴ rake
jruby 1.6.7.2 (ruby-1.9.2-p312) (2012-05-01 26e08ba) (OpenJDK 64-Bit Server VM 1.7.0_03) [linux-amd64-java]
/home/jesse/.rvm/gems/jruby-1.6.7.2@gf/gems/flexmock-minitest-1.0.1/lib/flexmock/minitest.rb:4 warning: already initialized constant VERSION
Run options: --seed 44751

# Running tests:

F.............NOTE: MiniTest::Unit::TestCase#assert_block is deprecated, use assert. It will be removed on 2013-01-01. Called from /home/jesse/.rvm/gems/jruby-1.6.7.2@gf/gems/flexmock-0.9.0/lib/flexmock/core_class_methods.rb:64:in `check'
NOTE: MiniTest::Unit::TestCase#assert_block is deprecated, use assert. It will be removed on 2013-01-01. Called from /home/jesse/.rvm/gems/jruby-1.6.7.2@gf/gems/flexmock-0.9.0/lib/flexmock/validators.rb:54:in `validate'
Unable to shutdown queue (1)
.......

Finished tests in 32.899000s, 0.6383 tests/s, 1.5198 assertions/s.

  1) Failure:
test_0001_provides a status structure for each live queue(GirlFriday::.shutdown!) [/home/jesse/projects/girl_friday/test/test_girl_friday.rb:32]:
Expected: 0
  Actual: 1

21 tests, 50 assertions, 1 failures, 0 errors, 0 skips
org.jruby.exceptions.RaiseException: (SystemExit) exit
rake aborted!
Command failed with status (-1): [/home/jesse/.rvm/rubies/jruby-1.6.7.2/bin/...]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by mperham** [comment]
I don't have time to look into this.  Either we ship it with the race condition or we don't ship it until someone else can track it down and fix it.  wdyt?

**Comment by jc00ke** [comment]
Personally I would prefer it fixed before shipping a release. Even though I use it on 1.9.3 I'm not a fan of shipping when we have a known, failing spec. That's my $0.02

**Comment by mperham** [comment]
Overrode you, dude.  When in doubt, :shipit:

**Comment by jc00ke** [comment]
Heh, well it is _your_ project :smile:
