### ISSUE TITLE
undefined method `with' for nil:NilClass

### ISSUE THREAD

**Issue by tetherit** [mperham/girl_friday#63]
I'm not quite sure what is causing this. I have a working queue that is processing tasks correctly, however I see these exceptions for some reason despite the task running correctly:

``` ruby
irb(main):023:0> a.save()
=> true
undefined method `with' for nil:NilClass
irb(main):024:0> /home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/persistence.rb:53:in `redis'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/persistence.rb:32:in `push'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/work_queue.rb:127:in `on_work'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/work_queue.rb:182:in `block (3 levels) in supervisor_loop'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:310:in `call'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:310:in `_receive'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:107:in `receive'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/work_queue.rb:177:in `block in supervisor_loop'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/work_queue.rb:176:in `loop'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/work_queue.rb:176:in `supervisor_loop'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/work_queue.rb:156:in `block in start'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:69:in `call'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:69:in `block (2 levels) in spawn'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:212:in `block in initialize'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:377:in `watchdog'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:212:in `initialize'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:66:in `new'
/home/deployer/xanview-portals/demo1/shared/bundle/ruby/1.9.1/gems/girl_friday-0.10.0/lib/girl_friday/actor.rb:66:in `block in spawn'
```

This is the task:

``` ruby
require 'connection_pool'
require 'redis'

redis_pool = ConnectionPool.new(:size => 5, :timeout => 5) { Redis.new }
defaults = { size: 1, store: GirlFriday::Store::Redis, store_config: { pool: redis_pool } }

GEOCODER_QUEUE = GirlFriday::WorkQueue.new(:geocoder, defaults) do |msg|
  object = msg[:model_name].constantize.find(msg[:id])

  # Don't geocode for local LAN addresses
  unless IPAddress(msg[:ip]).private? or msg[:ip] == "127.0.0.1"
    geo = Geocoder.search(msg[:ip])
    object.update_attributes!(
      coordinates: [geo[0].longitude, geo[0].latitude],
      country: geo[0].country,
      country_code: geo[0].country_code,
      city: geo[0].city
    )
  end
end
```

And the "msg" passed to the queue looks like this:

``` ruby
GEOCODER_QUEUE.push(model_name: self.class.model_name, id: self.id, ip: remote_ip)
```

Any ideas what is causing this?

**Comment by mperham** [comment]
No idea, looks fine to me.

**Comment by tetherit** [comment]
Ah, I think I figured it out, I'm trying to use default parameters for every GirlFriday queue:

``` ruby
defaults = { size: 1, store: GirlFriday::Store::Redis, store_config: { pool: redis_pool } }
```

However, girl_friday-0.10.0/lib/girl_friday/persistence.rb does this: 

``` ruby
@redis ||= @opts.delete(:pool)
```

So the next queue can't find the pool anymore.

Any reason why this is done? - any other way to pass defaults to all GirlFriday queues?

**Comment by tetherit** [comment]
I've changed the "defaults" hash to this:

``` ruby
$redis_pool = ConnectionPool.new(:size => 5, :timeout => 5) { Redis.new }
def default_queue(name, &block)
  GirlFriday::WorkQueue.new(name, size: 1, store: GirlFriday::Store::Redis, 
    store_config: { pool: $redis_pool }, &block)
end
```

Seems to work!

Any better way to pass defaults?

**Comment by mperham** [comment]
Hmm, yeah, good point.  Want to submit a PR which removes the delete?

**Comment by jc00ke** [comment]
I'm the one that implemented the `ConnectionPool` support, and I don't know why I used `#delete` :confused: 
I hadn't thought of your use case. My bad!
